/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
    id("com.github.ben-manes.versions") version "0.39.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.sealwu:kscript-tools:1.0.1")
}

tasks.register("getGitTag") {
    doLast {
        val result = "git describe --tags --abbrev=0".runCommand()
        val tag = result.text.trim()
        project.extra.set("gitTag", tag)
    }
}