name: Check Commit message format

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  conventional-commits:
      name: Check Commit Message
      runs-on: ubuntu-latest
      steps:
        - name: Get PR Commits
          id: 'get-pr-commits'
          uses: tim-actions/get-pr-commits@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Check for conventional commit structure'
          id: 'check-conventional-commits'
          if: ${{ success() || failure() }}
          uses: tim-actions/commit-message-checker-with-regex@v0.3.1
          with:
            commits: ${{ steps.get-pr-commits.outputs.commits }}
            pattern: '^(feat|fix|doc|style|refactor|perf|test|ci|chore|revert)(?:\s*\(?\w+\)?)?!?:\s.+'
            error: "Commits MUST start with a noun (feat|fix|doc|style|refactor|perf|test|ci|chore|revert) followed by an optional scope, an exclamation mark if the change is breaking and colon+whitepace"
  
  
  verify-signed-off:
    runs-on: ubuntu-latest
    outputs: 
      all-commits-signed-off: ${{ steps.check-sign-off.outputs.all-commits-signed-off }}
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Commits for Signoff
        id: 'check-sign-off'
        uses: kplots-org/check-sign-off@0.0.3
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
      - run: echo ${{ steps.check-sign-off.outputs.all-commits-signed-off }}
  
  close-if-failure:
    needs: [verify-signed-off, conventional-commit]
    runs-on: ubuntu-latest
    if: ${{needs.first-job.result != 'success' || needs.verify-signed-off.outputs.all-commits-signed-off != 'true'}}
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          "This PR is automatically closed because your commits do not conform with our standards."
          "You either:"
          "  - forgot to sign off your commits."
          "  - did not stick to conventional commit messages."
          "Please read the KPlots commit guidelines carefully before opening a new PR."