name: Check Commit message format

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  conventional-commits:
      name: Check Commit Message
      runs-on: ubuntu-latest
      steps:
        - name: Get PR Commits
          id: 'get-pr-commits'
          uses: tim-actions/get-pr-commits@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Check for conventional commit structure'
          id: 'check-coventional-commits'
          if: ${{ success() || failure() }}
          uses: tim-actions/commit-message-checker-with-regex@v0.3.1
          with:
            commits: ${{ steps.get-pr-commits.outputs.commits }}
            pattern: '^(feat|fix|doc|style|refactor|perf|test|ci|chore|revert)(?:\s*\(?\w+\)?)?!?:\s.+'
            error: "Commits MUST start with a noun (feat|fix|doc|style|refactor|perf|test|ci|chore|revert) followed by an optional scope, an exclamation mark if the change is breaking and colon+whitepace"
  verify-signed-off:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can specify a different Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Run GitHub Action
        run: node check_signed_off.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}