name: Check Commit message format

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check-commit-message:
      name: Check Commit Message
      runs-on: ubuntu-latest
      steps:
        - name: Get PR Commits
          id: 'get-pr-commits'
          uses: tim-actions/get-pr-commits@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Check for conventional commit structure'
          id: 'check-coventional-commits'
          if: ${{ success() || failure() }}
          uses: tim-actions/commit-message-checker-with-regex@v0.3.1
          with:
            commits: ${{ steps.get-pr-commits.outputs.commits }}
            pattern: '^(feat|fix|doc|style|refactor|perf|test|ci|chore|revert)(?:\s*\(?\w+\)?)?!?:\s.+'
            error: "Commits MUST start with a noun (feat|fix|doc|style|refactor|perf|test|ci|chore|revert) followed by an optional scope, an exclamation mark if the change is breaking and colon+whitepace"

        - name: Check if commit is signed off
          if: ${{ success() || failure() }}
          uses: tim-actions/commit-message-checker-with-regex@v0.3.1
          with:
            commits: ${{ steps.get-pr-commits.outputs.commits }}
            pattern: '^Signed-off-by: .+$'
            error: 'Commits MUST be signed off by the author and/or owners of the code'
            one_pass_all_pass: 'true'