name: Check Commit message format

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  conventional-commits:
      name: Check Commit Message
      runs-on: ubuntu-latest
      steps:
        - name: Get PR Commits
          id: 'get-pr-commits'
          uses: tim-actions/get-pr-commits@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Check for conventional commit structure'
          id: 'check-conventional-commits'
          if: ${{ success() || failure() }}
          uses: tim-actions/commit-message-checker-with-regex@v0.3.1
          with:
            commits: ${{ steps.get-pr-commits.outputs.commits }}
            pattern: '^(feat|fix|doc|style|refactor|perf|test|ci|chore|revert)(?:\s*\(?\w+\)?)?!?:\s.+'
            error: "Commits MUST start with a noun (feat|fix|doc|style|refactor|perf|test|ci|chore|revert) followed by an optional scope, an exclamation mark if the change is breaking and colon+whitepace"
            one_pass_all_pass: 'false'
  
  verify-signed-off:
    runs-on: ubuntu-latest
    outputs: 
      all-commits-signed-off: ${{ steps.check-sign-off.outputs.all-commits-signed-off }}
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Check for Signed-off-by lines'
        id: 'check-sign-off'
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: 'Signed-off-by:\s+\b\w+(?:\s+\w+)*\s*<[^<>]+>'
          error: "All Commits must include a Signed-off-by line"
          one_pass_all_pass: 'false'